[package]
name = "rhai-fmt"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
rhai-rowan = { version = "0.1.0", path = "../rhai-rowan" }
rowan = "0.15.19"
schemars = { version = "1.2.2", optional = true }
serde = { version = "1.0.229", features = ["derive"] }
tracing = "0.1.44"

[dev-dependencies]
criterion = "0.8.2"
insta = "1.48.0"
test-case = "3.3.1"
tracing-subscriber = "0.3.23"

[features]
schema = ["schemars"]

[[bench]]
name = "fmt"
harness = false
